### PR TITLE
Themed icon support for Android 13

### PR DESCRIPTION
**Pull request by Altonss**
I haven't tested if it works and how it renders, so this is only a first try :)
Also @francoisfds what do you think about switching to vector graphics for the icons like in https://github.com/CatimaLoyalty/Android/pull/987/files ?

### CODE REVIEW

**Comment by francoisfds** [comment]
Hello @Altonss thank you for the contribution.

I cannot test these changes on Android 13 right now but I will soon !

For the record I designed vector graphics already (https://github.com/francoisfds/BikeSharingHub/commit/a6f4e415aace65a32f49f5c78537aa21431baf45) which are in the current release 2.0.6. But you have reported an issue with them : https://github.com/francoisfds/BikeSharingHub/issues/6#issuecomment-1079669562

To avoid this issue, I recently split icons depending on the Android version, to create adaptive icons but I switch back to PNGs. It's true that using the vectorised form is better.

**Comment by Altonss** [comment]
> To avoid this issue, I recently split icons depending on the Android version, to create adaptive icons but I switch back to PNGs. It's true that using the vectorised form is better.

Why you know arePNGs used for the adaptive icons, is it because of #6 ?

**Comment by francoisfds** [comment]
Yes I switched back to PNGs because of #6.

**Comment by francoisfds** [comment]
Tested on Android 13, the icon is well displayed when themed icons are enforced :+1: 
I merge, thank you @Altonss

**Pull request merged**
